stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: your-docker-image-name
  API_KEY: your-api-key-value
  DATABASE_URL: your-database-url

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE npm test

deploy:
  stage: deploy
  script:
    - docker push $DOCKER_IMAGE


